spring:
  application:
    name: test_crud

  profiles:
    active: dev

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: app-pool
      maximum-pool-size: 5      # 서비스당 3~5 권장(데모 환경)
      minimum-idle: 2
      idle-timeout: 30000       # 30s
      max-lifetime: 1800000     # 30m < Azure LB/TCP idle보다 짧게
      keepalive-time: 300000    # 5m 주기 keepalive
      connection-timeout: 30000 # 30s
      data-source-properties:
        # Azure PG ??
        ssl: true
        sslmode: require
        tcpKeepAlive: true
        reWriteBatchedInserts: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      types:
        json:
          enabled: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.time_zone: UTC
    show-sql: false

  jackson:
    time-zone: Asia/Seoul
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  sql:
    init:
      mode: never

server:
  port: 8080
  forward-headers-strategy: framework

logging:
  level:
    root: INFO
    com.kt.damim: DEBUG

# Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html